# Name of the action
name: MongoDB Backup

# Controls when the action will run. 
on:
  # Triggers the workflow on cron schedule
  schedule:
    - cron: '0 0 * * *' # at UTC 00:00
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "backup"
  backup:
    name: 'MongoDB Backup'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2

    - shell: bash
      # Populate env variables from github secrets
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      # Runs a set of commands using the runners shell
      run: |
        sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
        mkdir swiftex_backup
        sudo chmod +x ./scripts/sync.sh
        ./scripts/sync.sh $MONGO_URI $DROPBOX_TOKEN